### ISSUE TITLE
Final TODO

### ISSUE THREAD

**Issue by lidavidm** [lidavidm/cs6360#88]
- [x] Rocketship sprite/animation
- [x] Final two levels
- [x] Pick up/put down animation
- [x] Make sure no levels use old repeat block
- [x] Make sure all levels are consistent (in terms of what blocks are available)
- [x] Make sure constructors work across all levels
- [x] Logging backend (blocked on upstream)
- [x] Animate rescue
- [x] Add pretest image
- [x] Rescue level: should instantiate robot
- [x] force a method definition in iron level (?)
